// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvZ971kzksVl73lOf2FcmgfG7AS12ZM00',
    appId: '1:610395104712:web:b74b3e2ef7ecd44682ccfd',
    messagingSenderId: '610395104712',
    projectId: 'attendance-tracker-5d550',
    authDomain: 'attendance-tracker-5d550.firebaseapp.com',
    storageBucket: 'attendance-tracker-5d550.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3nDWmtuENB7kbqod3ZZK8y318pacAi7M',
    appId: '1:610395104712:android:61c6d9479ce3df3882ccfd',
    messagingSenderId: '610395104712',
    projectId: 'attendance-tracker-5d550',
    storageBucket: 'attendance-tracker-5d550.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjz5TgBs1qaGXIHiRIarq_ykJadRB4QGA',
    appId: '1:610395104712:ios:3aaaef7f68936a3a82ccfd',
    messagingSenderId: '610395104712',
    projectId: 'attendance-tracker-5d550',
    storageBucket: 'attendance-tracker-5d550.firebasestorage.app',
    iosBundleId: 'com.example.attendanceTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjz5TgBs1qaGXIHiRIarq_ykJadRB4QGA',
    appId: '1:610395104712:ios:3aaaef7f68936a3a82ccfd',
    messagingSenderId: '610395104712',
    projectId: 'attendance-tracker-5d550',
    storageBucket: 'attendance-tracker-5d550.firebasestorage.app',
    iosBundleId: 'com.example.attendanceTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvZ971kzksVl73lOf2FcmgfG7AS12ZM00',
    appId: '1:610395104712:web:eb14c65b2117ef9782ccfd',
    messagingSenderId: '610395104712',
    projectId: 'attendance-tracker-5d550',
    authDomain: 'attendance-tracker-5d550.firebaseapp.com',
    storageBucket: 'attendance-tracker-5d550.firebasestorage.app',
  );
}
